// RobotBuilder Version: 0.0.2
//
// This file was generated by RobotBuilder. It contains sections of
// code that are automatically generated and assigned by robotbuilder.
// These sections will be updated in the future when you export to
// C++ from RobotBuilder. Do not put any code or make any change in
// the blocks indicating autogenerated code or it will be lost on an
// update. Deleting the comments indicating the section will prevent
// it from being updated in th future.
#include "RobotMap.h"
#include "LiveWindow/LiveWindow.h"
// BEGIN AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=ALLOCATION
SpeedController* RobotMap::indexerIndexerController = NULL;
SpeedController* RobotMap::launcherLauncherController = NULL;
SpeedController* RobotMap::launcherLauncherController2 = NULL;
SpeedController* RobotMap::fireFireController = NULL;
SpeedController* RobotMap::driveTrainLeftMotor = NULL;
SpeedController* RobotMap::driveTrainRightMotor = NULL;
RobotDrive* RobotMap::driveTrainRobotDrive21 = NULL;
    // END AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=ALLOCATION
void RobotMap::init() {
	// BEGIN AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=CONSTRUCTORS
	LiveWindow* lw = LiveWindow::GetInstance();
	indexerIndexerController = new Jaguar(1, 4);
	lw->AddActuator("Indexer", "IndexerController", (Jaguar*) indexerIndexerController);
	
	launcherLauncherController = new Jaguar(1, 3);
	lw->AddActuator("Launcher", "LauncherController", (Jaguar*) launcherLauncherController);
	
	launcherLauncherController2 = new Jaguar(1, 6);
	lw->AddActuator("Launcher", "LauncherController2", (Jaguar*) launcherLauncherController2);
	
	fireFireController = new Jaguar(1, 5);
	lw->AddActuator("Fire", "FireController", (Jaguar*) fireFireController);
	
	driveTrainLeftMotor = new Victor(1, 1);
	lw->AddActuator("DriveTrain", "LeftMotor", (Victor*) driveTrainLeftMotor);
	
	driveTrainRightMotor = new Victor(1, 2);
	lw->AddActuator("DriveTrain", "RightMotor", (Victor*) driveTrainRightMotor);
	
	driveTrainRobotDrive21 = new RobotDrive(driveTrainRightMotor, driveTrainLeftMotor);
	
	driveTrainRobotDrive21->SetSafetyEnabled(true);
        driveTrainRobotDrive21->SetExpiration(0.1);
        driveTrainRobotDrive21->SetSensitivity(0.5);
        driveTrainRobotDrive21->SetMaxOutput(1.0);
        driveTrainRobotDrive21->SetInvertedMotor(RobotDrive::kRearLeftMotor, true);
        driveTrainRobotDrive21->SetInvertedMotor(RobotDrive::kRearRightMotor, true);        
    // END AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=CONSTRUCTORS
}
