// RobotBuilder Version: 0.0.2
//
// This file was generated by RobotBuilder. It contains sections of
// code that are automatically generated and assigned by robotbuilder.
// These sections will be updated in the future when you export to
// C++ from RobotBuilder. Do not put any code or make any change in
// the blocks indicating autogenerated code or it will be lost on an
// update. Deleting the comments indicating the section will prevent
// it from being updated in th future.
#include "FireDisc.h"
FireDisc::FireDisc() {
	// Use requires() here to declare subsystem dependencies
	// eg. requires(chassis);
	// BEGIN AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=REQUIRES
	Requires(Robot::fire);
    // END AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=REQUIRES
	SetTimeout(1.4);
}
// Called just before this Command runs the first time
void FireDisc::Initialize() {
	Robot::fire->Forward();
}
// Called repeatedly when this Command is scheduled to run
void FireDisc::Execute() {
	if(TimeSinceInitialized() < .7)
		Robot::fire->Forward();
	else
		Robot::fire->Backward();
}
// Make this return true when this Command no longer needs to run execute()
bool FireDisc::IsFinished() {
	return IsTimedOut();
}
// Called once after isFinished returns true
void FireDisc::End() {
	Robot::fire->Stop();

}
// Called when another command which requires one or more of the same
// subsystems is scheduled to run
void FireDisc::Interrupted() {
	Robot::fire->Stop();
}
